## Week 2

### Exercise:
Use and experience methods from previous lessons with given data. Try to search for other pandas methods to analyze the data such as `groupby()` and `read_csv()`.

In [2]:
# You can find covid related data under project's data folder 
base_url = "C:/Users/oztur/deneme-folder/ada-lovelace-academy/data/covid/"
infected_dataset_url = base_url + "time_series_covid19_confirmed_global.csv"
recovered_dataset_url = base_url + "time_series_covid19_recovered_global.csv"
deaths_dataset_url = base_url + "time_series_covid19_deaths_global.csv"

#### Solution:

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Your code goes here
df_infected = pd.read_csv(infected_dataset_url)
df_recovered = pd.read_csv(recovered_dataset_url)
df_deaths = pd.read_csv(deaths_dataset_url)

In [5]:
df_infected.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,19551,20342,20917,21459,22142,22890,23546,24102,24766,25527
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,1232,1246,1263,1299,1341,1385,1416,1464,1521,1590
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,10050,10154,10265,10382,10484,10589,10698,10810,10919,11031
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,852,852,852,852,852,852,853,853,853,853
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,88,91,92,96,113,118,130,138,140,142

In [6]:
df_infected.dtypes

Province/State     object
Country/Region     object
Lat               float64
Long              float64
1/22/20             int64
                   ...
6/11/20             int64
6/12/20             int64
6/13/20             int64
6/14/20             int64
6/15/20             int64
Length: 150, dtype: object

In [7]:
grouped_infected = df_infected.groupby('Country/Region').sum()
print(grouped_infected.head())

               Province/State      Lat     Long  1/22/20  1/23/20  1/24/20  \
Country/Region
Afghanistan                 0  33.0000  65.0000        0        0        0
Albania                     0  41.1533  20.1683        0        0        0
Algeria                     0  28.0339   1.6596        0        0        0
Andorra                     0  42.5063   1.5218        0        0        0
Angola                      0 -11.2027  17.8739        0        0        0

                1/25/20  1/26/20  1/27/20  1/28/20  ...  6/6/20  6/7/20  \
Country/Region                                      ...
Afghanistan           0        0        0        0  ...   19551   20342
Albania               0        0        0        0  ...    1232    1246
Algeria               0        0        0        0  ...   10050   10154
Andorra               0        0        0        0  ...     852     852
Angola                0        0        0        0  ...      88      91

                6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  \
Country/Region
Afghanistan      20917   21459    22142    22890    23546    24102    24766
Albania           1263    1299     1341     1385     1416     1464     1521
Algeria          10265   10382    10484    10589    10698    10810    10919
Andorra            852     852      852      852      853      853      853
Angola              92      96      113      118      130      138      140

                6/15/20
Country/Region
Afghanistan       25527
Albania            1590
Algeria           11031
Andorra             853
Angola              142

[5 rows x 149 columns]

In [8]:
grouped_infected = df_infected.groupby('Country/Region').sum()
grouped_recovered = df_recovered.groupby('Country/Region').sum()
grouped_deaths = df_deaths.groupby('Country/Region').sum()

print("Grouped Infected Data:")
print(grouped_infected.head())

print("\nGrouped Recovered Data:")
print(grouped_recovered.head())

print("\nGrouped Deaths Data:")
print(grouped_deaths.head())

Grouped Infected Data:
               Province/State      Lat     Long  1/22/20  1/23/20  1/24/20  \
Country/Region
Afghanistan                 0  33.0000  65.0000        0        0        0
Albania                     0  41.1533  20.1683        0        0        0
Algeria                     0  28.0339   1.6596        0        0        0
Andorra                     0  42.5063   1.5218        0        0        0
Angola                      0 -11.2027  17.8739        0        0        0

                1/25/20  1/26/20  1/27/20  1/28/20  ...  6/6/20  6/7/20  \
Country/Region                                      ...
Afghanistan           0        0        0        0  ...   19551   20342
Albania               0        0        0        0  ...    1232    1246
Algeria               0        0        0        0  ...   10050   10154
Andorra               0        0        0        0  ...     852     852
Angola                0        0        0        0  ...      88      91

                6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  \
Country/Region
Afghanistan      20917   21459    22142    22890    23546    24102    24766
Albania           1263    1299     1341     1385     1416     1464     1521
Algeria          10265   10382    10484    10589    10698    10810    10919
Andorra            852     852      852      852      853      853      853
Angola              92      96      113      118      130      138      140

                6/15/20
Country/Region
Afghanistan       25527
Albania            1590
Algeria           11031
Andorra             853
Angola              142

[5 rows x 149 columns]

Grouped Recovered Data:
               Province/State      Lat     Long  1/22/20  1/23/20  1/24/20  \
Country/Region
Afghanistan                 0  33.0000  65.0000        0        0        0
Albania                     0  41.1533  20.1683        0        0        0
Algeria                     0  28.0339   1.6596        0        0        0
Andorra                     0  42.5063   1.5218        0        0        0
Angola                      0 -11.2027  17.8739        0        0        0

                1/25/20  1/26/20  1/27/20  1/28/20  ...  6/6/20  6/7/20  \
Country/Region                                      ...
Afghanistan           0        0        0        0  ...    1830    1875
Albania               0        0        0        0  ...     925     938
Algeria               0        0        0        0  ...    6631    6717
Andorra               0        0        0        0  ...     741     744
Angola                0        0        0        0  ...      24      24

                6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  \
Country/Region
Afghanistan       2171    2651     3013     3326     3928     4201     4725
Albania            945     960      980     1001     1034     1039     1044
Algeria           6799    6951     7074     7255     7322     7420     7606
Andorra            751     757      759      780      781      781      781
Angola              38      38       40       41       42       61       61

                6/15/20
Country/Region
Afghanistan        5164
Albania            1055
Algeria            7735
Andorra             789
Angola               64

[5 rows x 149 columns]

Grouped Deaths Data:
               Province/State      Lat     Long  1/22/20  1/23/20  1/24/20  \
Country/Region
Afghanistan                 0  33.0000  65.0000        0        0        0
Albania                     0  41.1533  20.1683        0        0        0
Algeria                     0  28.0339   1.6596        0        0        0
Andorra                     0  42.5063   1.5218        0        0        0
Angola                      0 -11.2027  17.8739        0        0        0

                1/25/20  1/26/20  1/27/20  1/28/20  ...  6/6/20  6/7/20  \
Country/Region                                      ...
Afghanistan           0        0        0        0  ...     327     357
Albania               0        0        0        0  ...      34      34
Algeria               0        0        0        0  ...     698     707
Andorra               0        0        0        0  ...      51      51
Angola                0        0        0        0  ...       4       4

                6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  \
Country/Region
Afghanistan        369     384      405      426      446      451      471
Albania             34      34       34       35       36       36       36
Algeria            715     724      732      741      751      760      767
Andorra             51      51       51       51       51       51       51
Angola               4       4        4        5        5        6        6

                6/15/20
Country/Region
Afghanistan         478
Albania              36
Algeria             777
Andorra              51
Angola                6

[5 rows x 149 columns]

In [13]:
# Filter data for specific countries
countries = ['US', 'India', 'Brazil']  
filtered_infected = df_infected[df_infected['Country/Region'].isin(countries)]

# Grouping by Country/Region and finding maximum cases for specific dates
max_cases_specific_countries = filtered_infected.groupby('Country/Region')[['6/9/20', '6/13/20']].max()
print("Max Cases for Specific Dates in Selected Countries:")
print(max_cases_specific_countries)

Max Cases for Specific Dates in Selected Countries:
                 6/9/20  6/13/20
Country/Region
Brazil           739503   850514
India            276146   320922
US              1979868  2074526

In [16]:
start_date = '5/1/20'
end_date = '8/1/20'

# Filter the data for the specified time interval and 'Country/Region' column
date_range_columns = df_deaths.columns[(df_deaths.columns >= start_date) & (df_deaths.columns <= end_date)]
filtered_deaths = df_deaths[['Country/Region'] + date_range_columns.tolist()]

# Grouping by Country/Region and finding the sum of deaths for the specified time interval
sum_deaths_time_interval = filtered_deaths.groupby('Country/Region').sum()
print(f"Sum of Deaths for {start_date} to {end_date}:")
print(sum_deaths_time_interval.head())

Sum of Deaths for 5/1/20 to 8/1/20:
                5/1/20  5/2/20  5/3/20  5/4/20  5/5/20  5/6/20  5/7/20  \
Country/Region
Afghanistan         68      72      85      90      95     104     106
Albania             31      31      31      31      31      31      31
Algeria            453     459     463     465     470     476     483
Andorra             43      44      45      45      46      46      47
Angola               2       2       2       2       2       2       2

                5/8/20  5/9/20  5/10/20  ...  6/6/20  6/7/20  6/8/20  6/9/20  \
Country/Region                           ...
Afghanistan        109     115      120  ...     327     357     369     384
Albania             31      31       31  ...      34      34      34      34
Algeria            488     494      502  ...     698     707     715     724
Andorra             47      48       48  ...      51      51      51      51
Angola               2       2        2  ...       4       4       4       4

                6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  6/15/20
Country/Region
Afghanistan         405      426      446      451      471      478
Albania              34       35       36       36       36       36
Algeria             732      741      751      760      767      777
Andorra              51       51       51       51       51       51
Angola                4        5        5        6        6        6

[5 rows x 46 columns]